siteSettings:
    kind: panel.form
    name: siteSettings
    label: Template1 Settings
    method: POST
    contentType: json
    url: /xapi/template1/prefs
    contents:
        ${template1Names}
        ${template1Types}

template1Names:
    kind: panel.input.text
    name: template1Names
    label: Template1 Names
    validation: id-strict max-length:64 onblur

template1Types:
    kind: panel.input.text
    name: template1Types
    label: Template1 Types
    validation: id-strict max-length:64 onblur
